import React, { useState } from 'react';
import { Challan, Customer, Product, User } from '../types';
import { createOrUpdateChallan, confirmChallan, generateChallanNumber } from '../services/storage';
import { FileText, Plus, Search, Eye, Download, CheckCircle2, AlertCircle, Trash2, ShieldAlert, X } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ChallansPageProps {
  challans: Challan[];
  customers: Customer[];
  products: Product[];
  onRefresh: () => void;
  currentUser: User;
}

export const ChallansPage: React.FC<ChallansPageProps> = ({
  challans,
  customers,
  products,
  onRefresh,
  currentUser
}) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('ALL');

  // New / Edit Challan Modal
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedCustomerId, setSelectedCustomerId] = useState<string>('');
  const [challanNotes, setChallanNotes] = useState('');
  const [items, setItems] = useState<{ productId: string; quantity: number }[]>([
    { productId: products[0]?.id || '', quantity: 1 }
  ]);
  const [formError, setFormError] = useState<string | null>(null);

  // Detail / View Modal
  const [viewChallan, setViewChallan] = useState<Challan | null>(null);

  const filteredChallans = challans.filter(c => {
    const matchesSearch =
      c.challanNumber.toLowerCase().includes(searchTerm.toLowerCase()) ||
      c.customerName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      c.createdBy.toLowerCase().includes(searchTerm.toLowerCase());

    const matchesStatus = statusFilter === 'ALL' || c.status === statusFilter;

    return matchesSearch && matchesStatus;
  });

  const handleOpenCreateModal = () => {
    if (customers.length === 0) {
      alert('Please add at least one customer first.');
      return;
    }
    if (products.length === 0) {
      alert('Please add at least one product to catalog first.');
      return;
    }
    setSelectedCustomerId(customers[0].id);
    setItems([{ productId: products[0].id, quantity: 1 }]);
    setChallanNotes('');
    setFormError(null);
    setIsModalOpen(true);
  };

  const handleAddItemRow = () => {
    const nextProd = products.find(p => !items.some(i => i.productId === p.id)) || products[0];
    setItems([...items, { productId: nextProd.id, quantity: 1 }]);
  };

  const handleRemoveItemRow = (index: number) => {
    if (items.length <= 1) return;
    setItems(items.filter((_, i) => i !== index));
  };

  const handleItemChange = (index: number, field: 'productId' | 'quantity', value: any) => {
    const updated = [...items];
    if (field === 'productId') {
      updated[index].productId = value;
    } else {
      updated[index].quantity = Math.max(1, Number(value));
    }
    setItems(updated);
  };

  const handleSaveChallan = (targetStatus: 'Draft' | 'Confirmed') => {
    setFormError(null);

    const res = createOrUpdateChallan({
      customerId: selectedCustomerId,
      items,
      status: targetStatus,
      notes: challanNotes
    });

    if (!res.success) {
      setFormError(res.message);
      return;
    }

    onRefresh();
    setIsModalOpen(false);
  };

  const handleConfirmDirect = (challanId: string) => {
    const res = confirmChallan(challanId);
    if (!res.success) {
      alert(`Stock Error: ${res.message}`);
      return;
    }
    onRefresh();
  };

  // Export PDF Invoice / Challan
  const handleExportPDF = (challan: Challan) => {
    const doc = new jsPDF();

    // Brand Header
    doc.setFillColor(79, 70, 229);
    doc.rect(0, 0, 210, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('NEXUS DISTRIBUTORS LTD.', 14, 18);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('OFFICIAL SALES DELIVERY CHALLAN', 14, 25);

    // Meta Details Box
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`Challan No: ${challan.challanNumber}`, 14, 42);
    doc.text(`Status: ${challan.status.toUpperCase()}`, 140, 42);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Issued Date: ${challan.createdAt}`, 14, 48);
    doc.text(`Generated By: ${challan.createdBy}`, 14, 54);

    // Customer Billing Box
    doc.setFillColor(241, 245, 249);
    doc.rect(14, 62, 182, 28, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('DELIVER TO CUSTOMER:', 18, 70);

    doc.setFont('helvetica', 'normal');
    doc.text(`Business: ${challan.customerName}`, 18, 76);
    doc.text(`Contact Phone: ${challan.customerMobile || 'N/A'}`, 18, 82);
    doc.text(`Address: ${challan.customerAddress || 'N/A'}`, 110, 76);

    // Line Items Table
    const tableData = challan.items.map((item, idx) => [
      idx + 1,
      item.productName,
      item.sku,
      `₹${item.unitPrice.toLocaleString('en-IN')}`,
      item.quantity,
      `₹${item.total.toLocaleString('en-IN')}`
    ]);

    autoTable(doc, {
      startY: 96,
      head: [['#', 'Product Description', 'SKU Code', 'Unit Price', 'Qty', 'Total (INR)']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255], fontStyle: 'bold' },
      styles: { fontSize: 9 }
    });

    // Summary Totals
    const finalY = (doc as any).lastAutoTable.previous.finalY + 10;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(`Total Units Shipped: ${challan.totalQuantity}`, 14, finalY);
    doc.text(`Grand Total Amount: INR ₹${challan.totalAmount.toLocaleString('en-IN')}`, 130, finalY);

    if (challan.notes) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.text(`Special Notes: ${challan.notes}`, 14, finalY + 10);
    }

    // Footer Signatures
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text('-----------------------------', 20, finalY + 35);
    doc.text('Authorized Signatory', 20, finalY + 40);

    doc.text('-----------------------------', 140, finalY + 35);
    doc.text('Customer Receiver Signature', 140, finalY + 40);

    doc.save(`Sales_Challan_${challan.challanNumber}.pdf`);
  };

  return (
    <div>
      <div className="page-header">
        <div>
          <h1 className="page-title">Sales Challan Module</h1>
          <p className="page-subtitle">Generate goods dispatch challans, validate stock levels, auto-deduct inventory, and export invoices.</p>
        </div>
        <div>
          {(currentUser.role === 'Admin' || currentUser.role === 'Sales') && (
            <button className="btn btn-primary" onClick={handleOpenCreateModal}>
              <Plus size={16} /> Create Sales Challan
            </button>
          )}
        </div>
      </div>

      {/* Filter Toolbar */}
      <div className="card" style={{ marginBottom: '1.5rem', padding: '1rem' }}>
        <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap', alignItems: 'center' }}>
          <div className="search-box" style={{ flex: 1 }}>
            <Search className="search-icon" />
            <input
              type="text"
              className="form-control"
              placeholder="Search challan number, customer name, creator..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>

          <div>
            <select
              className="form-control"
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              style={{ minWidth: 150 }}
            >
              <option value="ALL">All Statuses</option>
              <option value="Draft">Draft</option>
              <option value="Confirmed">Confirmed</option>
              <option value="Cancelled">Cancelled</option>
            </select>
          </div>
        </div>
      </div>

      {/* Challans Table */}
      <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
        <div className="table-container">
          <table className="custom-table">
            <thead>
              <tr>
                <th>Challan #</th>
                <th>Customer</th>
                <th>Items & Quantities</th>
                <th>Total Value</th>
                <th>Status</th>
                <th>Created Date</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredChallans.length === 0 ? (
                <tr>
                  <td colSpan={7} style={{ textAlign: 'center', padding: '3rem', color: 'var(--text-muted)' }}>
                    No sales challans recorded.
                  </td>
                </tr>
              ) : (
                filteredChallans.map((ch) => (
                  <tr key={ch.id}>
                    <td style={{ fontFamily: 'var(--font-mono)', fontWeight: 700, color: 'var(--primary)' }}>
                      {ch.challanNumber}
                    </td>
                    <td>
                      <div style={{ fontWeight: 700 }}>{ch.customerName}</div>
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>By: {ch.createdBy}</div>
                    </td>
                    <td>
                      <div style={{ fontSize: '0.85rem' }}>
                        <strong>{ch.totalQuantity} units</strong> ({ch.items.length} line items)
                      </div>
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-dim)' }}>
                        {ch.items.map(i => `${i.productName} (${i.quantity})`).join(', ').substring(0, 35)}...
                      </div>
                    </td>
                    <td style={{ fontWeight: 700 }}>₹{ch.totalAmount.toLocaleString('en-IN')}</td>
                    <td>
                      <span className={`badge badge-${ch.status === 'Confirmed' ? 'success' : ch.status === 'Draft' ? 'warning' : 'danger'}`}>
                        {ch.status}
                      </span>
                    </td>
                    <td style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>{ch.createdAt}</td>
                    <td>
                      <div style={{ display: 'flex', gap: '0.4rem' }}>
                        <button
                          className="btn btn-sm btn-secondary"
                          onClick={() => setViewChallan(ch)}
                          title="View Details"
                        >
                          <Eye size={14} />
                        </button>
                        {ch.status === 'Draft' && (currentUser.role === 'Admin' || currentUser.role === 'Sales') && (
                          <button
                            className="btn btn-sm btn-primary"
                            onClick={() => handleConfirmDirect(ch.id)}
                            title="Confirm Challan & Deduct Stock"
                          >
                            Confirm Stock
                          </button>
                        )}
                        <button
                          className="btn btn-sm btn-outline"
                          onClick={() => handleExportPDF(ch)}
                          title="Export PDF Invoice / Delivery Challan"
                        >
                          <Download size={14} /> PDF
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Create Sales Challan Modal */}
      {isModalOpen && (
        <div className="modal-overlay" onClick={() => setIsModalOpen(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()} style={{ maxWidth: '750px' }}>
            <div className="modal-header">
              <h3 className="modal-title">Generate New Sales Challan</h3>
              <button className="btn btn-secondary btn-sm" onClick={() => setIsModalOpen(false)}>
                <X size={16} />
              </button>
            </div>

            <div className="modal-body">
              {formError && (
                <div style={{ padding: '0.85rem 1rem', borderRadius: 'var(--radius-md)', background: 'var(--danger-bg)', border: '1px solid var(--danger)', color: 'var(--danger)', fontSize: '0.85rem', marginBottom: '1.25rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <AlertCircle size={18} />
                  <div>
                    <strong>Stock Validation Failed:</strong> {formError}
                  </div>
                </div>
              )}

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1rem' }}>
                <div className="form-group">
                  <label className="form-label">Auto-Generated Challan Number</label>
                  <input
                    type="text"
                    className="form-control"
                    disabled
                    style={{ fontFamily: 'var(--font-mono)', fontWeight: 700 }}
                    value={generateChallanNumber()}
                  />
                </div>

                <div className="form-group">
                  <label className="form-label">Select CRM Customer *</label>
                  <select
                    className="form-control"
                    value={selectedCustomerId}
                    onChange={(e) => setSelectedCustomerId(e.target.value)}
                  >
                    {customers.map(c => (
                      <option key={c.id} value={c.id}>
                        {c.businessName} ({c.name}) - {c.type}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              {/* Multi-Product Items Table */}
              <div style={{ marginBottom: '1rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                  <label className="form-label" style={{ marginBottom: 0 }}>Product Line Items</label>
                  <button type="button" className="btn btn-sm btn-secondary" onClick={handleAddItemRow}>
                    <Plus size={14} /> Add Line Item
                  </button>
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                  {items.map((item, idx) => {
                    const prod = products.find(p => p.id === item.productId);
                    const isOverStock = prod && prod.currentStock < item.quantity;
                    return (
                      <div
                        key={idx}
                        style={{
                          display: 'grid',
                          gridTemplateColumns: '2fr 1fr 1fr 40px',
                          gap: '0.75rem',
                          alignItems: 'center',
                          background: isOverStock ? 'var(--danger-bg)' : 'var(--bg-tertiary)',
                          padding: '0.75rem',
                          borderRadius: 'var(--radius-md)',
                          border: isOverStock ? '1px solid var(--danger)' : '1px solid var(--border-color)'
                        }}
                      >
                        <div>
                          <select
                            className="form-control"
                            value={item.productId}
                            onChange={(e) => handleItemChange(idx, 'productId', e.target.value)}
                          >
                            {products.map(p => (
                              <option key={p.id} value={p.id}>
                                {p.name} (Stock: {p.currentStock}) - ₹{p.unitPrice}
                              </option>
                            ))}
                          </select>
                        </div>

                        <div>
                          <input
                            type="number"
                            className="form-control"
                            min={1}
                            placeholder="Qty"
                            value={item.quantity}
                            onChange={(e) => handleItemChange(idx, 'quantity', e.target.value)}
                          />
                        </div>

                        <div style={{ fontWeight: 700, fontSize: '0.9rem', textAlign: 'right' }}>
                          ₹{((prod?.unitPrice || 0) * item.quantity).toLocaleString('en-IN')}
                        </div>

                        <div>
                          <button
                            type="button"
                            className="btn btn-sm btn-secondary"
                            onClick={() => handleRemoveItemRow(idx)}
                            disabled={items.length <= 1}
                            style={{ padding: '0.4rem' }}
                          >
                            <Trash2 size={15} color="var(--danger)" />
                          </button>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>

              <div className="form-group">
                <label className="form-label">Challan Notes / Special Instructions</label>
                <textarea
                  className="form-control"
                  rows={2}
                  value={challanNotes}
                  onChange={(e) => setChallanNotes(e.target.value)}
                  placeholder="Transport vehicle number, dispatch dock notes..."
                />
              </div>
            </div>

            <div className="modal-footer">
              <button className="btn btn-secondary" onClick={() => setIsModalOpen(false)}>
                Cancel
              </button>
              <button
                type="button"
                className="btn btn-secondary"
                onClick={() => handleSaveChallan('Draft')}
              >
                Save as Draft
              </button>
              <button
                type="button"
                className="btn btn-primary"
                onClick={() => handleSaveChallan('Confirmed')}
              >
                Save & Confirm (Deduct Stock)
              </button>
            </div>
          </div>
        </div>
      )}

      {/* View Challan Detail Modal */}
      {viewChallan && (
        <div className="modal-overlay" onClick={() => setViewChallan(null)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()} style={{ maxWidth: '650px' }}>
            <div className="modal-header">
              <div>
                <span className={`badge badge-${viewChallan.status === 'Confirmed' ? 'success' : viewChallan.status === 'Draft' ? 'warning' : 'danger'}`}>
                  {viewChallan.status}
                </span>
                <h3 className="modal-title" style={{ marginTop: '0.2rem', fontFamily: 'var(--font-mono)' }}>
                  {viewChallan.challanNumber}
                </h3>
              </div>
              <button className="btn btn-secondary btn-sm" onClick={() => setViewChallan(null)}>
                <X size={16} />
              </button>
            </div>

            <div className="modal-body">
              <div style={{ background: 'var(--bg-tertiary)', padding: '1rem', borderRadius: 'var(--radius-md)', marginBottom: '1.25rem' }}>
                <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 700 }}>CUSTOMER</div>
                <div style={{ fontWeight: 700, fontSize: '1.05rem' }}>{viewChallan.customerName}</div>
                <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>{viewChallan.customerAddress}</div>
              </div>

              <h4 style={{ fontSize: '0.9rem', fontWeight: 700, marginBottom: '0.5rem' }}>Line Items Breakdown:</h4>
              <div className="table-container" style={{ marginBottom: '1.25rem' }}>
                <table className="custom-table">
                  <thead>
                    <tr>
                      <th>Product</th>
                      <th>SKU</th>
                      <th>Unit Price</th>
                      <th>Qty</th>
                      <th>Subtotal</th>
                    </tr>
                  </thead>
                  <tbody>
                    {viewChallan.items.map((item, idx) => (
                      <tr key={idx}>
                        <td style={{ fontWeight: 600 }}>{item.productName}</td>
                        <td style={{ fontFamily: 'var(--font-mono)', fontSize: '0.8rem' }}>{item.sku}</td>
                        <td>₹{item.unitPrice}</td>
                        <td style={{ fontWeight: 700 }}>{item.quantity}</td>
                        <td style={{ fontWeight: 700 }}>₹{item.total.toLocaleString('en-IN')}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem', background: 'var(--primary-light)', borderRadius: 'var(--radius-md)' }}>
                <div>
                  <div style={{ fontSize: '0.8rem', color: 'var(--primary)', fontWeight: 600 }}>TOTAL QUANTITY</div>
                  <div style={{ fontSize: '1.25rem', fontWeight: 800, color: 'var(--primary)' }}>{viewChallan.totalQuantity} units</div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontSize: '0.8rem', color: 'var(--primary)', fontWeight: 600 }}>GRAND TOTAL</div>
                  <div style={{ fontSize: '1.5rem', fontWeight: 800, color: 'var(--primary)' }}>₹{viewChallan.totalAmount.toLocaleString('en-IN')}</div>
                </div>
              </div>
            </div>

            <div className="modal-footer">
              <button className="btn btn-outline" onClick={() => handleExportPDF(viewChallan)}>
                <Download size={15} /> Export PDF
              </button>
              <button className="btn btn-secondary" onClick={() => setViewChallan(null)}>
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
